from database.database import Database
from models import ProductType, ProductSubType

class ProductSubTypes():
    revision: str = '_2024_08_18_093345'

    def __init__(self):
        database = Database()
        database.seed([
            ProductSubType(type=database.get(ProductType(type='Овощи')).id, sub_type='Огурцы'),
            ProductSubType(type=database.get(ProductType(type='Овощи')).id, sub_type='Помидоры'),
            ProductSubType(type=database.get(ProductType(type='Овощи')).id, sub_type='Помидоры черри'),
            ProductSubType(type=database.get(ProductType(type='Овощи')).id, sub_type='Салат'),
            ProductSubType(type=database.get(ProductType(type='Овощи')).id, sub_type='Баклажан'),
            ProductSubType(type=database.get(ProductType(type='Овощи')).id, sub_type='Кабачок'),
            ProductSubType(type=database.get(ProductType(type='Овощи')).id, sub_type='Лук репчатый'),
            ProductSubType(type=database.get(ProductType(type='Овощи')).id, sub_type='Лук красный'),
            ProductSubType(type=database.get(ProductType(type='Овощи')).id, sub_type='Лук зелёный'),
            ProductSubType(type=database.get(ProductType(type='Овощи')).id, sub_type='Перец чили'),
            ProductSubType(type=database.get(ProductType(type='Овощи')).id, sub_type='Перец сладкий'),
            ProductSubType(type=database.get(ProductType(type='Овощи')).id, sub_type='Картофель'),
            ProductSubType(type=database.get(ProductType(type='Овощи')).id, sub_type='Капуста белокочанная'),
            ProductSubType(type=database.get(ProductType(type='Овощи')).id, sub_type='Капуста брюссельская'),
            ProductSubType(type=database.get(ProductType(type='Овощи')).id, sub_type='Капуста брокколи'),
            ProductSubType(type=database.get(ProductType(type='Овощи')).id, sub_type='Капуста цветная'),
            ProductSubType(type=database.get(ProductType(type='Фрукты и ягоды')).id, sub_type='Мандарины'),
            ProductSubType(type=database.get(ProductType(type='Фрукты и ягоды')).id, sub_type='Апельсины'),
            ProductSubType(type=database.get(ProductType(type='Фрукты и ягоды')).id, sub_type='Бананы'),
            ProductSubType(type=database.get(ProductType(type='Фрукты и ягоды')).id, sub_type='Грейпфрут'),
            ProductSubType(type=database.get(ProductType(type='Фрукты и ягоды')).id, sub_type='Арбуз'),
            ProductSubType(type=database.get(ProductType(type='Фрукты и ягоды')).id, sub_type='Дыня'),
            ProductSubType(type=database.get(ProductType(type='Фрукты и ягоды')).id, sub_type='Клубника'),
            ProductSubType(type=database.get(ProductType(type='Фрукты и ягоды')).id, sub_type='Лимон'),
            ProductSubType(type=database.get(ProductType(type='Фрукты и ягоды')).id, sub_type='Сливы'),
            ProductSubType(type=database.get(ProductType(type='Фрукты и ягоды')).id, sub_type='Киви'),
            ProductSubType(type=database.get(ProductType(type='Фрукты и ягоды')).id, sub_type='Виноград'),
            ProductSubType(type=database.get(ProductType(type='Фрукты и ягоды')).id, sub_type='Яблоки'),
            ProductSubType(type=database.get(ProductType(type='Фрукты и ягоды')).id, sub_type='Нектарины'),
            ProductSubType(type=database.get(ProductType(type='Фрукты и ягоды')).id, sub_type='Персики'),
            ProductSubType(type=database.get(ProductType(type='Фрукты и ягоды')).id, sub_type='Груши'),
            ProductSubType(type=database.get(ProductType(type='Молочные продукты')).id, sub_type='Сыр'),
            ProductSubType(type=database.get(ProductType(type='Молочные продукты')).id, sub_type='Сырки'),
            ProductSubType(type=database.get(ProductType(type='Молочные продукты')).id, sub_type='Творог'),
            ProductSubType(type=database.get(ProductType(type='Молочные продукты')).id, sub_type='Творожная масса'),
            ProductSubType(type=database.get(ProductType(type='Молочные продукты')).id, sub_type='Творожный десерт'),
            ProductSubType(type=database.get(ProductType(type='Молочные продукты')).id, sub_type='Йогурт ложковый'),
            ProductSubType(type=database.get(ProductType(type='Молочные продукты')).id, sub_type='Йогурт питьевой'),
            ProductSubType(type=database.get(ProductType(type='Молочные продукты')).id, sub_type='Молоко'),
            ProductSubType(type=database.get(ProductType(type='Молочные продукты')).id, sub_type='Топлёное молоко'),
            ProductSubType(type=database.get(ProductType(type='Молочные продукты')).id, sub_type='Кефир'),
            ProductSubType(type=database.get(ProductType(type='Молочные продукты')).id, sub_type='Ряженка'),
            ProductSubType(type=database.get(ProductType(type='Молочные продукты')).id, sub_type='Варенец'),
            ProductSubType(type=database.get(ProductType(type='Мясные продукты')).id, sub_type='Фарш'),
            ProductSubType(type=database.get(ProductType(type='Мясные продукты')).id, sub_type='Ветчина'),
            ProductSubType(type=database.get(ProductType(type='Мясные продукты')).id, sub_type='Карбонад'),
            ProductSubType(type=database.get(ProductType(type='Мясные продукты')).id, sub_type='Колбаса'),
            ProductSubType(type=database.get(ProductType(type='Мясные продукты')).id, sub_type='Готовое мясо'),
            ProductSubType(type=database.get(ProductType(type='Мясные продукты')).id, sub_type='Сырое мясо'),
            ProductSubType(type=database.get(ProductType(type='Мясные продукты')).id, sub_type='Сосиски'),
            ProductSubType(type=database.get(ProductType(type='Мясные продукты')).id, sub_type='Сардельки'),
            ProductSubType(type=database.get(ProductType(type='Мясные продукты')).id, sub_type='Шпикачки'),
            ProductSubType(type=database.get(ProductType(type='Замороженные продукты')).id, sub_type='Пельмени'),
            ProductSubType(type=database.get(ProductType(type='Замороженные продукты')).id, sub_type='Вареники'),
            ProductSubType(type=database.get(ProductType(type='Замороженные продукты')).id, sub_type='Хинкали'),
            ProductSubType(type=database.get(ProductType(type='Замороженные продукты')).id, sub_type='Наггетсы'),
            ProductSubType(type=database.get(ProductType(type='Замороженные продукты')).id, sub_type='Котлеты'),
            ProductSubType(type=database.get(ProductType(type='Замороженные продукты')).id, sub_type='Голубцы'),
            ProductSubType(type=database.get(ProductType(type='Замороженные продукты')).id, sub_type='Фаршированные перцы'),
            ProductSubType(type=database.get(ProductType(type='Замороженные продукты')).id, sub_type='Долма'),
            ProductSubType(type=database.get(ProductType(type='Замороженные продукты')).id, sub_type='Овощная смесь'),
            ProductSubType(type=database.get(ProductType(type='Замороженные продукты')).id, sub_type='Замороженные ягоды'),
            ProductSubType(type=database.get(ProductType(type='Замороженные продукты')).id, sub_type='Фруктовая смесь'),
            ProductSubType(type=database.get(ProductType(type='Замороженные продукты')).id, sub_type='Драники'),
            ProductSubType(type=database.get(ProductType(type='Замороженные продукты')).id, sub_type='Сырники'),
            ProductSubType(type=database.get(ProductType(type='Замороженные продукты')).id, sub_type='Чебуреки'),
            ProductSubType(type=database.get(ProductType(type='Замороженные продукты')).id, sub_type='Пицца'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Хлеб'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Сок'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Квас'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Специи'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Минеральная вода'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Газированная вода'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Томатная паста'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Рис'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Макароны'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Гречка'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Булгур'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Сахар'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Фруктоза'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Соль'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Соус'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Кетчуп'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Сладкие батончики'),
            ProductSubType(type=database.get(ProductType(type='Бакалея')).id, sub_type='Конфеты'),
            ProductSubType(type=database.get(ProductType(type='Алкогольные напитки')).id, sub_type='Пиво'),
            ProductSubType(type=database.get(ProductType(type='Алкогольные напитки')).id, sub_type='Водка'),
            ProductSubType(type=database.get(ProductType(type='Алкогольные напитки')).id, sub_type='Виски'),
            ProductSubType(type=database.get(ProductType(type='Алкогольные напитки')).id, sub_type='Вино'),
            ProductSubType(type=database.get(ProductType(type='Личная гигиена')).id, sub_type='Мыло'),
            ProductSubType(type=database.get(ProductType(type='Личная гигиена')).id, sub_type='Шампунь'),
            ProductSubType(type=database.get(ProductType(type='Личная гигиена')).id, sub_type='Зубная паста'),
            ProductSubType(type=database.get(ProductType(type='Личная гигиена')).id, sub_type='Зубная щётка'),
            ProductSubType(type=database.get(ProductType(type='Личная гигиена')).id, sub_type='Бритвенные станки'),
            ProductSubType(type=database.get(ProductType(type='Личная гигиена')).id, sub_type='Средство для бритья'),
            ProductSubType(type=database.get(ProductType(type='Личная гигиена')).id, sub_type='Туалетная бумага'),
            ProductSubType(type=database.get(ProductType(type='Личная гигиена')).id, sub_type='Влажные салфетки'),
            ProductSubType(type=database.get(ProductType(type='Личная гигиена')).id, sub_type='Салфетки'),
            ProductSubType(type=database.get(ProductType(type='Уборка')).id, sub_type='Губки'),
            ProductSubType(type=database.get(ProductType(type='Уборка')).id, sub_type='Перчатки'),
            ProductSubType(type=database.get(ProductType(type='Уборка')).id, sub_type='Тряпки'),
            ProductSubType(type=database.get(ProductType(type='Уборка')).id, sub_type='Освежитель воздуха'),
            ProductSubType(type=database.get(ProductType(type='Уборка')).id, sub_type='Ролик для одежды'),
            ProductSubType(type=database.get(ProductType(type='Уборка')).id, sub_type='Чистящий порошок'),
            ProductSubType(type=database.get(ProductType(type='Уборка')).id, sub_type='Стиральный порошок'),
            ProductSubType(type=database.get(ProductType(type='Уборка')).id, sub_type='Средство для мытья полов'),
            ProductSubType(type=database.get(ProductType(type='Уборка')).id, sub_type='Средство для мытья туалета'),
            ProductSubType(type=database.get(ProductType(type='Уборка')).id, sub_type='Средство для мытья посуды')
        ])
