services:
  redis:
    image: "redis:latest"
    container_name: redis_service
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - fastapi-network

  mysql:
    image: "mysql:latest"
    container_name: mysql_service
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fastapi-network

  fastapi_template:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_template
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - mysql
    networks:
      - fastapi-network

volumes:
  redis_data:
  mysql_data:

networks:
  fastapi-network:
    driver: bridge