version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: redis_service
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - fastapi-network

  fastapi_template:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_template
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - fastapi-network

volumes:
  redis_data:

networks:
  fastapi-network:
    driver: bridge