services:
  redis:
    image: "redis:latest"
    container_name: redis_service
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "${REDIS_ROOT_PASSWORD}"]
    networks:
      - spending-tracker-network

  mysql:
    image: "mysql:latest"
    container_name: mysql_service
    restart: unless-stopped
    tty: true
    environment:
      DB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      DB_NAME: "${DB_NAME}"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spending-tracker-network

  spending_tracker_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spending_tracker_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - mysql
    networks:
      - spending-tracker-network

volumes:
  redis_data:
  mysql_data:

networks:
  spending-tracker-network:
    driver: bridge